/**
 * Argentina Business Advisor skill — AFIP, monotributo, labor, taxes.
 * Owner: HeadIntelligenceRisk agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface ArgentinaBusinessAdvice { registration: { steps: string[]; entityTypes: string[]; costs: string }; taxes: { iva: string; ganancias: string; regimes: string[]; afip: string[] }; labor: { minimumWage: string; benefits: string[]; termination: string; contributions: string }; compliance: { permits: string[]; afipObligations: string[]; electronicInvoicing: string[] }; actionSteps: string[]; }
export interface ArgentinaBusinessOptions { businessType: string; employees?: number; revenue?: number; question?: string; language?: string; }
const SYSTEM = 'You are an Argentina business advisor. Expert in AFIP, CUIT, Monotributo, IVA, Ganancias, labor law (LCT), ANSES contributions. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "registration": { "steps": [string], "entityTypes": [string], "costs": string }, "taxes": { "iva": string, "ganancias": string, "regimes": [string], "afip": [string] }, "labor": { "minimumWage": string, "benefits": [string], "termination": string, "contributions": string }, "compliance": { "permits": [string], "afipObligations": [string], "electronicInvoicing": [string] }, "actionSteps": [string] }';
export async function adviseArgentinaBusiness(options: ArgentinaBusinessOptions, llmClient?: LLMClient): Promise<ArgentinaBusinessAdvice> {
  if (llmClient) { const prompt = `Argentina business advice for: ${options.businessType}\nEmployees: ${options.employees ?? 0}\n${options.question ? `Question: ${options.question}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as ArgentinaBusinessAdvice; } catch { /* fall through */ } }
  return { registration: { steps: ['Obtener CUIT en AFIP', 'Inscribirse en Monotributo o Responsable Inscripto', 'Inscripción en Ingresos Brutos (provincial)', 'Habilitación comercial municipal', 'Alta de empleados en AFIP (F931)'], entityTypes: ['SAS (Sociedad por Acciones Simplificada) — 24h digital', 'SRL (Sociedad de Responsabilidad Limitada)', 'SA (Sociedad Anónima)', 'Monotributista (persona física)'], costs: 'SAS: $100-300 USD (digital). SRL/SA: $500-1500 USD' }, taxes: { iva: '21% alícuota general (10.5% reducida, 27% servicios)', ganancias: '25-35% escala progresiva sociedades / personas', regimes: ['Monotributo: cuota fija mensual (categorías A-K)', 'Responsable Inscripto: IVA + Ganancias + IIBB', 'Régimen simplificado PyME'], afip: ['Factura electrónica obligatoria', 'DDJJ mensuales (IVA F2002, Ganancias)', 'SIRE (retenciones y percepciones)', 'Libro IVA digital'] }, labor: { minimumWage: 'SMVM actualizado por Consejo del Salario (consultar AFIP)', benefits: ['Aguinaldo (SAC): 2 pagos/año (junio y diciembre)', 'Vacaciones: 14-35 días según antigüedad', 'Licencia por maternidad: 90 días', 'ART (riesgos del trabajo)'], termination: 'Indemnización: 1 sueldo por año de antigüedad (base: mejor remuneración mensual)', contributions: 'Empleador: ~26% (jubilación, obra social, ANSSAL, ART). Empleado: ~17%' }, compliance: { permits: ['Habilitación comercial municipal', 'Inscripción en Ingresos Brutos', 'Certificado de aptitud ambiental (según rubro)', 'Habilitación de bomberos'], afipObligations: ['Facturación electrónica (AFIP)', 'DDJJ mensual IVA + retenciones', 'DDJJ anual Ganancias + Bienes Personales', 'F931 cargas sociales (si tiene empleados)'], electronicInvoicing: ['Factura electrónica obligatoria para todos', 'Tipos: A, B, C, M, E (según emisor/receptor)', 'Usar AFIP web o software autorizado', 'CAE (Código de Autorización Electrónico) por factura'] }, actionSteps: ['Obtener CUIT en AFIP', 'Evaluar Monotributo vs Responsable Inscripto', 'Inscribirse en Ingresos Brutos provincial', 'Configurar facturación electrónica en AFIP'] };
}
