/**
 * Blog Post Advisor skill — Blog strategy, SEO writing, content structure.
 * Owner: CMO agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface BlogPostAdvice { strategy: { topics: string[]; frequency: string; pillars: string[] }; structure: { outline: string[]; seoTips: string[]; ctaPlacement: string[] }; promotion: { channels: string[]; repurposing: string[]; internalLinks: string[] }; metrics: { kpis: string[]; tools: string[]; benchmarks: string[] }; actionSteps: string[]; }
export interface BlogPostOptions { niche: string; targetAudience?: string; currentTraffic?: string; challenges?: string; language?: string; }
const SYSTEM = 'You are a blog content strategist for LatAm SMBs. SEO-driven blog strategy, content structure, promotion. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "strategy": { "topics": [string], "frequency": string, "pillars": [string] }, "structure": { "outline": [string], "seoTips": [string], "ctaPlacement": [string] }, "promotion": { "channels": [string], "repurposing": [string], "internalLinks": [string] }, "metrics": { "kpis": [string], "tools": [string], "benchmarks": [string] }, "actionSteps": [string] }';
export async function adviseBlogPost(options: BlogPostOptions, llmClient?: LLMClient): Promise<BlogPostAdvice> {
  if (llmClient) { const prompt = `Blog strategy for: ${options.niche}\nAudience: ${options.targetAudience ?? 'SMB owners'}\n${options.challenges ? `Challenges: ${options.challenges}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as BlogPostAdvice; } catch { /* fall through */ } }
  return { strategy: { topics: ['Guías paso a paso de tu industria', 'Casos de éxito de clientes', 'Comparativas de productos/servicios', 'Tendencias del mercado local', 'FAQ respondidas en detalle'], frequency: '2 posts por semana (mínimo 1 para SEO)', pillars: ['Educación del cliente', 'Autoridad en el nicho', 'Conversión (bottom-funnel)'] }, structure: { outline: ['Título con keyword principal (H1)', 'Introducción con hook + promesa (150 words)', 'Subtítulos H2 cada 300 palabras', 'Bullet points para escaneo rápido', 'Conclusión + CTA'], seoTips: ['Keyword en título, URL, primer párrafo, H2', 'Meta description con CTA (max 155 chars)', 'Alt text en todas las imágenes', 'Internal links a 2-3 posts relacionados', 'Longitud ideal: 1500-2500 palabras'], ctaPlacement: ['After introduction (soft CTA)', 'Mid-article (contextual offer)', 'End of post (hard CTA)', 'Sidebar (evergreen offer)'] }, promotion: { channels: ['WhatsApp status/broadcast', 'Instagram carrusel (resumen visual)', 'Facebook grupo/página', 'Email newsletter', 'LinkedIn (si B2B)'], repurposing: ['Post → 5 tweets/posts para redes', 'Post → carrusel de Instagram', 'Post → script de video corto', 'Post → newsletter semanal', 'Post → respuesta de WhatsApp'], internalLinks: ['Enlazar a productos/servicios mencionados', 'Enlazar a posts pillar relacionados', 'Crear tabla de contenido con anclas'] }, metrics: { kpis: ['Tráfico orgánico (Google Search Console)', 'Tiempo en página (>2 min ideal)', 'Tasa de rebote (<65% ideal)', 'Conversiones desde blog'], tools: ['Google Search Console (gratis)', 'Google Analytics 4 (gratis)', 'Ubersuggest (freemium)', 'Ahrefs (premium)'], benchmarks: ['Mes 1-3: indexación y primeras impresiones', 'Mes 3-6: primeras posiciones page 2-3', 'Mes 6-12: tráfico orgánico constante'] }, actionSteps: ['Definir 3 pilares de contenido', 'Investigar 20 keywords con volumen local', 'Escribir primer post pilar (+2000 palabras)', 'Configurar Google Search Console'] };
}
