/**
 * Chile Business Advisor skill — SII, labor, taxes, business registration.
 * Owner: HeadIntelligenceRisk agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface ChileBusinessAdvice { registration: { steps: string[]; entityTypes: string[]; costs: string }; taxes: { iva: string; incomeRate: string; filings: string[]; sii: string[] }; labor: { minimumWage: string; benefits: string[]; termination: string; afp: string }; compliance: { permits: string[]; siiObligations: string[]; electronicInvoicing: string[] }; actionSteps: string[]; }
export interface ChileBusinessOptions { businessType: string; employees?: number; revenue?: number; question?: string; language?: string; }
const SYSTEM = 'You are a Chile business advisor. Expert in SII (Servicio de Impuestos Internos), Chilean labor code, business registration, IVA, Renta, AFP, Isapre. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "registration": { "steps": [string], "entityTypes": [string], "costs": string }, "taxes": { "iva": string, "incomeRate": string, "filings": [string], "sii": [string] }, "labor": { "minimumWage": string, "benefits": [string], "termination": string, "afp": string }, "compliance": { "permits": [string], "siiObligations": [string], "electronicInvoicing": [string] }, "actionSteps": [string] }';
export async function adviseChileBusiness(options: ChileBusinessOptions, llmClient?: LLMClient): Promise<ChileBusinessAdvice> {
  if (llmClient) { const prompt = `Chile business advice for: ${options.businessType}\nEmployees: ${options.employees ?? 0}\n${options.question ? `Question: ${options.question}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as ChileBusinessAdvice; } catch { /* fall through */ } }
  return { registration: { steps: ['Obtener RUT en SII (Inicio de Actividades)', 'Constituir sociedad ante notario', 'Inscribir en Registro de Comercio', 'Obtener patente municipal', 'Registrarse en inspección del trabajo'], entityTypes: ['SpA (Sociedad por Acciones) — más común', 'SRL (Sociedad de Responsabilidad Limitada)', 'EIRL (Empresa Individual)', 'Persona natural con giro'], costs: '$300-800 USD (incluye abogado y notario)' }, taxes: { iva: '19% sobre ventas (IVA)', incomeRate: '27% primera categoría (empresas) / progresivo personas', filings: ['F29 mensual (IVA + PPM)', 'F22 anual (renta)', 'DJ varias (informativas)'], sii: ['Boleta electrónica obligatoria', 'Factura electrónica obligatoria', 'Libros contables electrónicos', 'Timbraje digital en sii.cl'] }, labor: { minimumWage: '$460.000 CLP/mes (~$500 USD, 2024)', benefits: ['Vacaciones: 15 días hábiles/año', 'Aguinaldo (septiembre y diciembre)', 'Licencia maternal: 24 semanas', 'Seguro de cesantía'], termination: 'Indemnización: 1 mes por año (tope 11 años). Aviso previo 30 días.', afp: 'AFP: 10% empleado + comisión (~1.5%). Empleador: seguro invalidez 1.53%' }, compliance: { permits: ['Patente municipal (renovar anualmente)', 'Resolución sanitaria (alimentos/salud)', 'Certificado de informaciones previas', 'Permiso de edificación (si aplica)'], siiObligations: ['Inicio de actividades (dentro de 2 meses)', 'Emisión de DTE (documentos tributarios electrónicos)', 'Declaración mensual F29', 'Declaración anual F22'], electronicInvoicing: ['Factura electrónica obligatoria desde 2018', 'Usar software certificado por SII', 'Envío automático al SII', 'Guardar XML por 6 años'] }, actionSteps: ['Hacer Inicio de Actividades en sii.cl', 'Constituir SpA ante notario', 'Obtener patente municipal', 'Configurar facturación electrónica'] };
}
