/**
 * Costa Rica Business Advisor skill — Hacienda, CCSS, labor, taxes.
 * Owner: HeadIntelligenceRisk agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface CostaRicaBusinessAdvice { registration: { steps: string[]; entityTypes: string[]; costs: string }; taxes: { iva: string; incomeRate: string; filings: string[]; hacienda: string[] }; labor: { minimumWage: string; benefits: string[]; termination: string; ccss: string }; compliance: { permits: string[]; haciendaObligations: string[]; electronicInvoicing: string[] }; actionSteps: string[]; }
export interface CostaRicaBusinessOptions { businessType: string; employees?: number; revenue?: number; question?: string; language?: string; }
const SYSTEM = 'You are a Costa Rica business advisor. Expert in Ministerio de Hacienda, CCSS, labor code, IVA, renta, patentes, factura electrónica. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "registration": { "steps": [string], "entityTypes": [string], "costs": string }, "taxes": { "iva": string, "incomeRate": string, "filings": [string], "hacienda": [string] }, "labor": { "minimumWage": string, "benefits": [string], "termination": string, "ccss": string }, "compliance": { "permits": [string], "haciendaObligations": [string], "electronicInvoicing": [string] }, "actionSteps": [string] }';
export async function adviseCostaRicaBusiness(options: CostaRicaBusinessOptions, llmClient?: LLMClient): Promise<CostaRicaBusinessAdvice> {
  if (llmClient) { const prompt = `Costa Rica business advice for: ${options.businessType}\nEmployees: ${options.employees ?? 0}\n${options.question ? `Question: ${options.question}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as CostaRicaBusinessAdvice; } catch { /* fall through */ } }
  return { registration: { steps: ['Inscribir persona jurídica en Registro Nacional', 'Obtener cédula jurídica', 'Inscribirse como contribuyente en Hacienda (ATV)', 'Obtener patente municipal', 'Inscribir trabajadores en CCSS'], entityTypes: ['SRL (Sociedad de Responsabilidad Limitada)', 'SA (Sociedad Anónima)', 'Persona física con actividad lucrativa', 'Cooperativa'], costs: '$400-1200 USD (incluye abogado y notario)' }, taxes: { iva: '13% IVA general (reducido 4%, 2%, 1% según bienes)', incomeRate: '30% empresas / progresivo personas (0-25%)', filings: ['D-104 mensual (IVA)', 'D-101 anual (renta)', 'D-151 informativa anual', 'INDER 2% sobre utilidades'], hacienda: ['Factura electrónica obligatoria', 'ATV (Administración Tributaria Virtual)', 'Declaraciones en línea', 'Firma digital recomendada'] }, labor: { minimumWage: '₡367,000/mes mínimo genérico (~$670 USD, 2024)', benefits: ['Aguinaldo: 1 mes (pagar antes del 20 diciembre)', 'Vacaciones: 2 semanas/año', 'Cesantía: acumulación progresiva', 'Licencia maternidad: 4 meses'], termination: 'Preaviso: 1-3 meses según antigüedad. Cesantía: hasta 8 años acumulados.', ccss: 'CCSS: 26.5% empleador + 10.5% empleado (SEM + IVM + otros)' }, compliance: { permits: ['Patente municipal (anual)', 'Permiso sanitario (Ministerio de Salud)', 'Póliza de riesgos del trabajo (INS)', 'Permiso de uso de suelo'], haciendaObligations: ['Inscripción en ATV', 'Factura electrónica', 'D-104 mensual', 'D-101 anual'], electronicInvoicing: ['Obligatoria para todos los contribuyentes', 'Usar proveedor certificado por Hacienda', 'Tipos: FE (factura), TE (tiquete), NC, ND', 'XML firmado digitalmente'] }, actionSteps: ['Constituir sociedad ante notario', 'Inscribirse en Hacienda (ATV)', 'Obtener patente municipal', 'Configurar factura electrónica'] };
}
