/**
 * Cross-Border Trade Advisor skill — International trade, customs, regulations.
 * Owner: HeadIntelligenceRisk agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface CrossBorderTradeAdvice { regulations: { importRequirements: string[]; exportRequirements: string[]; tradeAgreements: string[] }; logistics: { shipping: string[]; customs: string[]; documentation: string[] }; payments: { methods: string[]; currency: string[]; compliance: string[] }; taxes: { duties: string[]; vatRules: string[]; transferPricing: string[] }; actionSteps: string[]; }
export interface CrossBorderTradeOptions { originCountry: string; destinationCountry: string; productType?: string; tradeVolume?: string; challenges?: string; language?: string; }
const SYSTEM = 'You are a cross-border trade expert for LatAm. Import/export regulations, customs, trade agreements, logistics, payments. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "regulations": { "importRequirements": [string], "exportRequirements": [string], "tradeAgreements": [string] }, "logistics": { "shipping": [string], "customs": [string], "documentation": [string] }, "payments": { "methods": [string], "currency": [string], "compliance": [string] }, "taxes": { "duties": [string], "vatRules": [string], "transferPricing": [string] }, "actionSteps": [string] }';
export async function adviseCrossBorderTrade(options: CrossBorderTradeOptions, llmClient?: LLMClient): Promise<CrossBorderTradeAdvice> {
  if (llmClient) { const prompt = `Cross-border trade advice: ${options.originCountry} → ${options.destinationCountry}\nProduct: ${options.productType ?? 'general'}\nVolume: ${options.tradeVolume ?? 'small'}\n${options.challenges ? `Challenges: ${options.challenges}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as CrossBorderTradeAdvice; } catch { /* fall through */ } }
  return { regulations: { importRequirements: ['Licencia de importación (según producto)', 'Clasificación arancelaria (código HS)', 'Certificado de origen', 'Registro sanitario (alimentos/medicamentos)', 'Certificado fitosanitario (agro)'], exportRequirements: ['Registro como exportador', 'Factura comercial + packing list', 'Certificado de origen (para preferencias arancelarias)', 'Permisos especiales (según producto)', 'Declaración aduanera de exportación'], tradeAgreements: ['USMCA (México-USA-Canadá)', 'Alianza del Pacífico (México, Colombia, Perú, Chile)', 'MERCOSUR (Brasil, Argentina, Uruguay, Paraguay)', 'CAFTA-DR (Centroamérica + República Dominicana + USA)', 'TLC bilaterales específicos'] }, logistics: { shipping: ['Marítimo: contenedor (más económico, 15-30 días)', 'Aéreo: carga (rápido, caro, perecederos)', 'Terrestre: camión (entre países vecinos)', 'Courier: DHL/FedEx (muestras, paquetes pequeños)'], customs: ['Agente aduanal requerido en la mayoría de países', 'Valoración aduanera: precio de transacción + flete + seguro', 'Inspección física aleatoria (zona primaria)', 'Liberación: 1-5 días hábiles promedio'], documentation: ['Factura comercial (detalle completo)', 'Bill of Lading / Air Waybill', 'Packing list', 'Certificado de origen', 'Declaración aduanera', 'Seguro de carga'] }, payments: { methods: ['Transferencia bancaria (SWIFT)', 'Carta de crédito (L/C): seguridad para ambos', 'Cobranza documentaria', 'PayPal / Payoneer (montos menores)', 'Cuenta en USD en banco corresponsal'], currency: ['Dólar USD: moneda estándar para comercio internacional', 'Considerar tipo de cambio al fijar precios', 'Cobertura cambiaria (forward) para montos grandes', 'Facturar en USD, cobrar en moneda local si necesario'], compliance: ['Regulaciones anti-lavado (cada país)', 'Reporte de operaciones internacionales', 'OFAC sanctions check (si involucra USA)', 'Transfer pricing documentation'] }, taxes: { duties: ['Arancel: 0-35% según producto y origen', 'Arancel preferencial con TLC (certificado de origen)', 'Arancel NMF (Nación Más Favorecida) sin TLC', 'Derechos compensatorios/antidumping (algunos productos)'], vatRules: ['IVA/IGV/ITBMS sobre base imponible + arancel', 'IVA importación pagado en aduana', 'Crédito fiscal recuperable (si empresa)', 'Zona libre: exención de IVA en algunos casos'], transferPricing: ['Precios entre empresas relacionadas deben ser arm\'s length', 'Documentación obligatoria en la mayoría de países', 'Métodos aceptados: CUP, RPM, CPM, TNMM, PSM', 'Declaración informativa anual'] }, actionSteps: ['Clasificar producto (código HS de 6-10 dígitos)', 'Verificar TLC aplicables y reglas de origen', 'Contratar agente aduanal en ambos países', 'Definir Incoterm (FOB, CIF, DDP más comunes)', 'Cotizar flete y seguro con 3 proveedores'] };
}
