/**
 * Document Archive Advisor skill — Document management, organization, compliance.
 * Owner: COO agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface DocumentArchiveAdvice { organization: { structure: string[]; naming: string[]; categories: string[] }; digitization: { tools: string[]; workflow: string[]; ocrTips: string[] }; compliance: { retention: string[]; backup: string[]; access: string[] }; automation: { workflows: string[]; templates: string[]; integrations: string[] }; actionSteps: string[]; }
export interface DocumentArchiveOptions { businessType: string; documentVolume?: string; currentSystem?: string; country?: string; language?: string; }
const SYSTEM = 'You are a document management and archiving specialist for LatAm SMBs. Organization, digitization, compliance, automation. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "organization": { "structure": [string], "naming": [string], "categories": [string] }, "digitization": { "tools": [string], "workflow": [string], "ocrTips": [string] }, "compliance": { "retention": [string], "backup": [string], "access": [string] }, "automation": { "workflows": [string], "templates": [string], "integrations": [string] }, "actionSteps": [string] }';
export async function adviseDocumentArchive(options: DocumentArchiveOptions, llmClient?: LLMClient): Promise<DocumentArchiveAdvice> {
  if (llmClient) { const prompt = `Document archive strategy for: ${options.businessType}\nVolume: ${options.documentVolume ?? 'medium'}\nCountry: ${options.country ?? 'LatAm'}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as DocumentArchiveAdvice; } catch { /* fall through */ } }
  return { organization: { structure: ['📁 Legal (contratos, permisos, actas)', '📁 Finanzas (facturas, recibos, estados)', '📁 RRHH (contratos, nómina, expedientes)', '📁 Clientes (propuestas, contratos, facturas)', '📁 Operaciones (SOPs, manuales, reportes)'], naming: ['YYYY-MM-DD_Tipo_Descripcion.ext', 'Ejemplo: 2024-01-15_Factura_ClienteX.pdf', 'Usar guiones bajos, no espacios', 'Incluir versión si aplica (v1, v2)'], categories: ['Documentos legales', 'Documentos financieros', 'Documentos de RRHH', 'Documentos de clientes', 'Documentos operativos'] }, digitization: { tools: ['Google Drive / OneDrive (almacenamiento)', 'Adobe Scan / CamScanner (escaneo móvil)', 'Kitz DocScan (OCR integrado)', 'Notion / Coda (base de datos de docs)'], workflow: ['Recibir documento físico → escanear mismo día', 'OCR → extraer datos clave → archivar', 'Vincular a cliente/proyecto en CRM', 'Destruir original si no es requerido legalmente'], ocrTips: ['Escanear a 300 DPI mínimo', 'Fondo claro, buena iluminación', 'Verificar texto extraído por OCR', 'Guardar original + versión OCR'] }, compliance: { retention: ['Facturas: 5-10 años según país', 'Contratos laborales: durante relación + 5 años', 'Documentos fiscales: 5 años mínimo', 'Actas constitutivas: permanente'], backup: ['Backup automático diario (cloud)', '1 copia local + 1 copia en la nube', 'Verificar integridad mensualmente', 'Plan de recuperación documentado'], access: ['Control de acceso por rol', 'Auditar quién accede a qué', 'Documentos sensibles: solo gerencia', 'Compartir con link temporal (no permanente)'] }, automation: { workflows: ['Auto-clasificar facturas recibidas por email', 'Alerta de vencimiento de contratos (30 días)', 'Auto-generar carpeta por nuevo cliente', 'Recordatorio de backup semanal'], templates: ['Plantilla de contrato de servicios', 'Plantilla de factura', 'Plantilla de NDA', 'Plantilla de propuesta comercial'], integrations: ['Email → auto-archive adjuntos', 'CRM → vincular docs a contactos', 'Contabilidad → facturas automáticas', 'WhatsApp → recibir y archivar docs'] }, actionSteps: ['Crear estructura de carpetas estándar', 'Escanear y archivar los 20 documentos más importantes', 'Configurar backup automático', 'Definir política de retención por tipo de documento'] };
}
