/**
 * Drip Campaign Advisor skill — Email/WhatsApp automated sequences.
 * Owner: CMO agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface DripCampaignAdvice { strategy: { sequences: string[]; triggers: string[]; segmentation: string[] }; content: { emailTemplates: string[]; whatsappTemplates: string[]; timing: string[] }; optimization: { abTests: string[]; metrics: string[]; automation: string[] }; tools: { recommended: string[]; integrations: string[]; pricing: string[] }; actionSteps: string[]; }
export interface DripCampaignOptions { businessType: string; goal?: string; listSize?: number; currentTools?: string; language?: string; }
const SYSTEM = 'You are a drip campaign and marketing automation expert for LatAm SMBs. Email + WhatsApp sequences, triggers, optimization. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "strategy": { "sequences": [string], "triggers": [string], "segmentation": [string] }, "content": { "emailTemplates": [string], "whatsappTemplates": [string], "timing": [string] }, "optimization": { "abTests": [string], "metrics": [string], "automation": [string] }, "tools": { "recommended": [string], "integrations": [string], "pricing": [string] }, "actionSteps": [string] }';
export async function adviseDripCampaign(options: DripCampaignOptions, llmClient?: LLMClient): Promise<DripCampaignAdvice> {
  if (llmClient) { const prompt = `Drip campaign strategy for: ${options.businessType}\nGoal: ${options.goal ?? 'nurture + convert'}\nList size: ${options.listSize ?? 'unknown'}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as DripCampaignAdvice; } catch { /* fall through */ } }
  return { strategy: { sequences: ['Bienvenida (5 emails, 14 días)', 'Nurture (8 emails, 30 días)', 'Ventas (3 emails, 7 días)', 'Onboarding post-compra (5 emails, 21 días)', 'Re-engagement (3 emails, 10 días)'], triggers: ['Suscripción a lista', 'Descarga de lead magnet', 'Carrito abandonado', 'Compra completada', 'Inactividad >30 días'], segmentation: ['Por fuente (WhatsApp, web, referido)', 'Por comportamiento (abrió, clic, compró)', 'Por valor (ticket promedio)', 'Por etapa del funnel'] }, content: { emailTemplates: ['Bienvenida: historia personal + qué esperar', 'Valor: tip práctico + caso de éxito', 'Social proof: testimonio + resultado', 'Oferta: descuento + urgencia + CTA', 'Última oportunidad: escasez + bonus'], whatsappTemplates: ['Bienvenida: saludo + menú de opciones', 'Recordatorio: pedido/cita/pago pendiente', 'Promo: oferta flash + link de pago', 'Follow-up: ¿cómo te fue con X?'], timing: ['Email: enviar 10am martes/jueves', 'WhatsApp: enviar 11am-1pm o 5-7pm', 'Esperar mínimo 2 días entre emails', 'WhatsApp: máximo 1 mensaje proactivo/semana'] }, optimization: { abTests: ['Subject lines (emoji vs no emoji)', 'Hora de envío (mañana vs tarde)', 'Largo del email (corto vs largo)', 'CTA (botón vs texto link)'], metrics: ['Open rate >25% (email)', 'Click rate >3% (email)', 'Reply rate >10% (WhatsApp)', 'Conversion rate >2%'], automation: ['Auto-tag basado en comportamiento', 'Lead scoring automático', 'Mover entre secuencias por triggers', 'Alertar a ventas cuando lead está caliente'] }, tools: { recommended: ['Mailchimp (email, plan gratis hasta 500)', 'Brevo (email + WhatsApp)', 'ActiveCampaign (avanzado)', 'Kitz (WhatsApp nativo)'], integrations: ['CRM (sincronizar contactos)', 'E-commerce (trigger por compra)', 'WhatsApp (mensajes automáticos)', 'Analytics (tracking UTM)'], pricing: ['Mailchimp: gratis hasta 500, $13/mes 500+', 'Brevo: gratis hasta 300 emails/día', 'ActiveCampaign: $29/mes'] }, actionSteps: ['Crear secuencia de bienvenida (5 emails)', 'Configurar trigger de carrito abandonado', 'Segmentar lista actual en 3-4 grupos', 'Escribir templates de WhatsApp para recordatorios'] };
}
