/**
 * Invoicing Advisor skill — Invoice management, payment terms, collections.
 * Owner: CFO agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface InvoicingAdvice { setup: { tools: string[]; requirements: string[]; templates: string[] }; process: { workflow: string[]; paymentTerms: string[]; numbering: string[] }; collection: { reminders: string[]; escalation: string[]; discounts: string[] }; compliance: { electronic: string[]; taxRules: string[]; recordKeeping: string[] }; actionSteps: string[]; }
export interface InvoicingOptions { businessType: string; country?: string; monthlyInvoices?: number; challenges?: string; language?: string; }
const SYSTEM = 'You are an invoicing and collections specialist for LatAm SMBs. Invoice management, payment terms, electronic invoicing compliance. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "setup": { "tools": [string], "requirements": [string], "templates": [string] }, "process": { "workflow": [string], "paymentTerms": [string], "numbering": [string] }, "collection": { "reminders": [string], "escalation": [string], "discounts": [string] }, "compliance": { "electronic": [string], "taxRules": [string], "recordKeeping": [string] }, "actionSteps": [string] }';
export async function adviseInvoicing(options: InvoicingOptions, llmClient?: LLMClient): Promise<InvoicingAdvice> {
  if (llmClient) { const prompt = `Invoicing strategy for: ${options.businessType}\nCountry: ${options.country ?? 'LatAm'}\nMonthly invoices: ${options.monthlyInvoices ?? 'unknown'}\n${options.challenges ? `Challenges: ${options.challenges}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as InvoicingAdvice; } catch { /* fall through */ } }
  return { setup: { tools: ['Kitz Invoice Generator (integrado)', 'Alegra (LatAm, factura electrónica)', 'Wave (gratis, básico)', 'Facturapi (México, CFDI automático)'], requirements: ['RFC/NIT/RUC del negocio', 'Datos fiscales completos', 'Sello digital (si aplica)', 'Cuenta bancaria para recibir pagos'], templates: ['Factura estándar (productos)', 'Factura de servicios (horas/proyecto)', 'Nota de crédito', 'Cotización / presupuesto'] }, process: { workflow: ['1. Crear factura al cerrar venta/servicio', '2. Enviar por email + WhatsApp', '3. Registrar en sistema contable', '4. Dar seguimiento al pago', '5. Emitir recibo al cobrar'], paymentTerms: ['Inmediato: servicios bajo $500', 'Net 15: clientes frecuentes', 'Net 30: clientes corporativos', '50% anticipo + 50% entrega: proyectos'], numbering: ['Formato: YYYY-NNNN (ej: 2024-0001)', 'Consecutivo sin saltos', 'Prefijo por tipo (FAC-, NC-, COT-)', 'Separar series por sucursal si aplica'] }, collection: { reminders: ['Día 0: enviar factura', 'Día 3: confirmar recepción', 'Día vencimiento: recordatorio amable', 'Día +7: recordatorio firme', 'Día +15: notificación formal'], escalation: ['1. WhatsApp amable', '2. Email formal', '3. Llamada telefónica', '4. Carta formal con plazo', '5. Suspender servicio / cobro judicial'], discounts: ['Pronto pago: 3-5% si paga en <7 días', 'Recargo: 1-3% mensual por mora', 'Pago en efectivo: descuento 2%', 'Paquete prepagado: descuento 10-15%'] }, compliance: { electronic: ['México: CFDI obligatorio (SAT)', 'Colombia: factura electrónica DIAN', 'Brasil: NF-e (Nota Fiscal eletrônica)', 'Panamá: facturación electrónica DGI (en transición)'], taxRules: ['Incluir desglose de impuestos (IVA/ITBMS/IVA)', 'Retenciones aplicables', 'Régimen fiscal del emisor', 'Datos fiscales completos del receptor'], recordKeeping: ['Guardar facturas 5-10 años', 'Backup digital mensual', 'Archivo por año y mes', 'Acceso rápido para auditorías'] }, actionSteps: ['Configurar herramienta de facturación electrónica', 'Crear 3 templates (producto, servicio, cotización)', 'Definir política de pagos y comunicar a clientes', 'Automatizar recordatorios de cobro'] };
}
