/**
 * Mail Merge Advisor skill — Personalized bulk communications.
 * Owner: CMO agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface MailMergeAdvice { setup: { dataSource: string[]; templates: string[]; personalization: string[] }; execution: { tools: string[]; workflow: string[]; testing: string[] }; channels: { email: string[]; whatsapp: string[]; print: string[] }; compliance: { optIn: string[]; unsubscribe: string[]; dataProtection: string[] }; actionSteps: string[]; }
export interface MailMergeOptions { useCase: string; recipientCount?: number; channels?: string; currentTools?: string; language?: string; }
const SYSTEM = 'You are a mail merge and personalized communications expert for LatAm SMBs. Bulk personalized emails, WhatsApp, letters. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "setup": { "dataSource": [string], "templates": [string], "personalization": [string] }, "execution": { "tools": [string], "workflow": [string], "testing": [string] }, "channels": { "email": [string], "whatsapp": [string], "print": [string] }, "compliance": { "optIn": [string], "unsubscribe": [string], "dataProtection": [string] }, "actionSteps": [string] }';
export async function adviseMailMerge(options: MailMergeOptions, llmClient?: LLMClient): Promise<MailMergeAdvice> {
  if (llmClient) { const prompt = `Mail merge strategy for: ${options.useCase}\nRecipients: ${options.recipientCount ?? 'unknown'}\nChannels: ${options.channels ?? 'email + WhatsApp'}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as MailMergeAdvice; } catch { /* fall through */ } }
  return { setup: { dataSource: ['Google Sheets / Excel con columnas estándar', 'CRM exportado (nombre, email, teléfono, empresa)', 'Segmentar por: ubicación, compra, industria', 'Limpiar datos: eliminar duplicados y errores'], templates: ['Saludo personalizado: Hola {nombre}', 'Referencia a compra: Tu pedido de {producto}', 'Mención de empresa: Para {empresa}', 'Oferta segmentada: {descuento}% especial para ti'], personalization: ['Nombre y empresa', 'Última compra o interacción', 'Monto pendiente o historial', 'Fecha relevante (aniversario, renovación)'] }, execution: { tools: ['Google Sheets + Mailchimp (email)', 'Brevo / Sendinblue (email + SMS)', 'Kitz broadcast (WhatsApp nativo)', 'Google Docs + complemento mail merge'], workflow: ['1. Preparar datos en spreadsheet limpio', '2. Crear template con variables {campo}', '3. Test con 5 contactos internos', '4. Enviar en lotes de 50-100', '5. Monitorear bounces y respuestas'], testing: ['Enviar prueba a ti mismo primero', 'Verificar personalización correcta', 'Probar en diferentes dispositivos', 'Revisar links y CTAs'] }, channels: { email: ['Subject personalizado: max 50 chars + {nombre}', 'Enviar 10am martes-jueves', 'Lote máximo: 200/hora (evitar spam filters)', 'Usar dominio verificado (SPF, DKIM, DMARC)'], whatsapp: ['Usar templates aprobados (Business API)', 'Broadcast lists: max 256 contactos', 'Personalizar primer mensaje manualmente', 'Incluir opción de responder o darse de baja'], print: ['Cartas personalizadas para clientes VIP', 'Certificados con nombre y logros', 'Etiquetas de envío personalizadas'] }, compliance: { optIn: ['Solo enviar a contactos con opt-in explícito', 'Registrar fecha y método de consentimiento', 'Double opt-in recomendado para email'], unsubscribe: ['Incluir link/opción de desuscripción en cada envío', 'Procesar bajas en <48 horas', 'Mantener lista de supresión actualizada'], dataProtection: ['Cumplir LGPD (Brasil), LFPDPPP (México), Ley 1581 (Colombia)', 'No compartir listas con terceros', 'Encriptar datos personales en tránsito'] }, actionSteps: ['Exportar y limpiar datos de contactos', 'Crear template de email con 3 variables personalizadas', 'Enviar test a 5 contactos internos', 'Lanzar primer envío a segmento más comprometido'] };
}
