/**
 * Mercado Libre Advisor skill — Listings, pricing, ads, reputation.
 * Owner: HeadGrowth agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface MercadoLibreAdvice { listings: { titleFormula: string; photoTips: string[]; descriptionStructure: string[] }; pricing: { strategy: string; shippingTips: string[]; competitiveAnalysis: string }; ads: { productAds: string[]; budgetTips: string[]; keywords: string[] }; reputation: { metrics: string[]; responseTime: string; disputeHandling: string[] }; actionSteps: string[]; }
export interface MercadoLibreOptions { productCategory: string; country?: string; monthlyOrders?: number; challenges?: string; language?: string; }
const SYSTEM = 'You are a Mercado Libre optimization expert for LatAm sellers. Listings, pricing, Product Ads, reputation building. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "listings": { "titleFormula": string, "photoTips": [string], "descriptionStructure": [string] }, "pricing": { "strategy": string, "shippingTips": [string], "competitiveAnalysis": string }, "ads": { "productAds": [string], "budgetTips": [string], "keywords": [string] }, "reputation": { "metrics": [string], "responseTime": string, "disputeHandling": [string] }, "actionSteps": [string] }';
export async function adviseMercadoLibre(options: MercadoLibreOptions, llmClient?: LLMClient): Promise<MercadoLibreAdvice> {
  if (llmClient) { const prompt = `Mercado Libre advice for: ${options.productCategory}\nCountry: ${options.country ?? 'Mexico'}\n${options.challenges ? `Challenges: ${options.challenges}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as MercadoLibreAdvice; } catch { /* fall through */ } }
  return { listings: { titleFormula: '[Marca] + [Producto] + [Atributo clave] + [Beneficio] (max 60 chars)', photoTips: ['Fondo blanco, 1200x1200px mínimo', 'Mínimo 6 fotos por producto', 'Incluir foto de escala/uso', 'Video de 15-30 segundos'], descriptionStructure: ['Beneficio principal en primera línea', 'Especificaciones técnicas en tabla', 'Incluir dimensiones y peso', 'FAQ con 5 preguntas comunes'] }, pricing: { strategy: 'Precio competitivo + envío gratis (absorber costo en precio)', shippingTips: ['Usar Mercado Envíos Full si >50 ventas/mes', 'Envío gratis en productos >$299 MXN', 'Empacar bien para evitar devoluciones'], competitiveAnalysis: 'Revisar top 5 vendedores de tu categoría semanalmente' }, ads: { productAds: ['Activar Product Ads en los 10 productos más vendidos', 'Presupuesto diario: 3-5% del margen por producto', 'Pausar ads en productos sin stock'], budgetTips: ['Empezar con $50 MXN/día', 'Escalar productos con ACOS < 15%', 'Revisar métricas cada 3 días'], keywords: ['Usar términos de búsqueda del reporte de Mercado Libre', 'Incluir sinónimos regionales', 'Agregar palabras negativas'] }, reputation: { metrics: ['Nivel: MercadoLíder (>60 ventas/mes)', 'Reputación verde: <2% reclamos', 'Envío: <48h promedio'], responseTime: 'Responder mensajes en <1 hora durante horario laboral', disputeHandling: ['Responder mediaciones en <24h', 'Ofrecer solución antes de escalamiento', 'Documentar todo con fotos'] }, actionSteps: ['Optimizar títulos de los 20 productos principales', 'Tomar fotos profesionales con fondo blanco', 'Activar Mercado Envíos para todos los productos', 'Configurar Product Ads con presupuesto inicial'] };
}
