/**
 * Personal Brand Builder skill — Founder branding, thought leadership, content.
 * Owner: CMO agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface PersonalBrandAdvice { identity: { positioning: string; narrative: string; values: string[] }; content: { platforms: string[]; contentMix: string[]; frequency: string }; visibility: { speakingOps: string[]; collaborations: string[]; mediaOutreach: string[] }; monetization: { pathways: string[]; timeline: string; metrics: string[] }; actionSteps: string[]; }
export interface PersonalBrandOptions { name: string; industry: string; expertise?: string; goals?: string; language?: string; }
const SYSTEM = 'You are a personal brand strategist for LatAm founders and entrepreneurs. Positioning, content strategy, thought leadership. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "identity": { "positioning": string, "narrative": string, "values": [string] }, "content": { "platforms": [string], "contentMix": [string], "frequency": string }, "visibility": { "speakingOps": [string], "collaborations": [string], "mediaOutreach": [string] }, "monetization": { "pathways": [string], "timeline": string, "metrics": [string] }, "actionSteps": [string] }';
export async function buildPersonalBrand(options: PersonalBrandOptions, llmClient?: LLMClient): Promise<PersonalBrandAdvice> {
  if (llmClient) { const prompt = `Personal brand strategy for: ${options.name}\nIndustry: ${options.industry}\nExpertise: ${options.expertise ?? 'general'}\n${options.goals ? `Goals: ${options.goals}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as PersonalBrandAdvice; } catch { /* fall through */ } }
  return { identity: { positioning: 'El/la experto(a) en [nicho] que ayuda a [audiencia] a lograr [resultado]', narrative: 'De [origen/reto] a [logro], ahora comparto [método] para que otros lo logren', values: ['Autenticidad', 'Generosidad con conocimiento', 'Resultados medibles', 'Comunidad sobre competencia'] }, content: { platforms: ['LinkedIn (pensamiento, artículos)', 'Instagram (behind-the-scenes, reels)', 'Twitter/X (opiniones, hilos)', 'YouTube (contenido largo, tutoriales)'], contentMix: ['40% educación (how-to, tips)', '30% historia personal (behind-the-scenes)', '20% prueba social (resultados, testimonios)', '10% promoción directa'], frequency: '5 posts/semana en plataforma principal, 2-3 en secundarias' }, visibility: { speakingOps: ['Podcasts del nicho (guest)', 'Eventos locales de emprendimiento', 'Webinars gratuitos mensuales', 'Meetups de la industria'], collaborations: ['Co-crear contenido con 3-5 cuentas similares', 'Entrevistas cruzadas', 'Proyectos conjuntos con marcas complementarias'], mediaOutreach: ['Notas de prensa para logros/hitos', 'Columna en medio digital del nicho', 'Aportar como fuente experta a periodistas'] }, monetization: { pathways: ['Consultoría premium', 'Curso/programa online', 'Comunidad de pago', 'Partnerships con marcas', 'Speaking fees'], timeline: 'Meses 1-3: audiencia. Meses 3-6: autoridad. Meses 6-12: monetización.', metrics: ['Seguidores → leads → clientes', 'Engagement rate >3%', 'Inbound leads/semana'] }, actionSteps: ['Definir positioning statement en 1 oración', 'Crear biografía unificada para todas las plataformas', 'Publicar 5 posts esta semana en plataforma principal', 'Contactar 3 podcasts para ser invitado'] };
}
