/**
 * Peru Business Advisor skill — SUNAT, labor, taxes, business registration.
 * Owner: HeadIntelligenceRisk agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface PeruBusinessAdvice { registration: { steps: string[]; entityTypes: string[]; costs: string }; taxes: { igv: string; incomeRate: string; regimes: string[]; sunat: string[] }; labor: { minimumWage: string; benefits: string[]; termination: string; essalud: string }; compliance: { permits: string[]; sunatObligations: string[]; electronicInvoicing: string[] }; actionSteps: string[]; }
export interface PeruBusinessOptions { businessType: string; employees?: number; revenue?: number; question?: string; language?: string; }
const SYSTEM = 'You are a Peru business advisor. Expert in SUNAT, RUC, IGV, Régimen MYPE, labor code (DL 728), EsSalud, AFP/ONP. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "registration": { "steps": [string], "entityTypes": [string], "costs": string }, "taxes": { "igv": string, "incomeRate": string, "regimes": [string], "sunat": [string] }, "labor": { "minimumWage": string, "benefits": [string], "termination": string, "essalud": string }, "compliance": { "permits": [string], "sunatObligations": [string], "electronicInvoicing": [string] }, "actionSteps": [string] }';
export async function advisePeruBusiness(options: PeruBusinessOptions, llmClient?: LLMClient): Promise<PeruBusinessAdvice> {
  if (llmClient) { const prompt = `Peru business advice for: ${options.businessType}\nEmployees: ${options.employees ?? 0}\n${options.question ? `Question: ${options.question}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as PeruBusinessAdvice; } catch { /* fall through */ } }
  return { registration: { steps: ['Obtener RUC en SUNAT (persona natural o jurídica)', 'Constituir empresa en SUNARP', 'Legalizar libros contables', 'Obtener licencia de funcionamiento municipal', 'Registrar en T-Registro (empleados)'], entityTypes: ['SAC (Sociedad Anónima Cerrada)', 'SRL (Sociedad de Responsabilidad Limitada)', 'EIRL (Empresa Individual)', 'Persona natural con negocio'], costs: '$200-600 USD (incluye notario y SUNARP)' }, taxes: { igv: '18% sobre ventas (IGV = 16% + IPM 2%)', incomeRate: '29.5% tercera categoría (empresas)', regimes: ['NRUS (Nuevo RUS): hasta S/96K/año, cuota fija', 'RER (Régimen Especial): hasta S/525K/año, 1.5% ventas', 'MYPE Tributario: hasta 1700 UIT, tasas reducidas', 'Régimen General: sin límite, 29.5%'], sunat: ['Declaración mensual PDT 621', 'DAOT anual', 'Libros electrónicos PLE/SLE'] }, labor: { minimumWage: 'S/1,025/mes (~$275 USD, 2024)', benefits: ['CTS: 1 sueldo/año (depósito mayo y noviembre)', 'Gratificaciones: julio y diciembre (1 sueldo c/u)', 'Vacaciones: 30 días/año', 'Asignación familiar: 10% del mínimo'], termination: 'Indemnización: 1.5 sueldos por año (tope 12 sueldos)', essalud: 'EsSalud: 9% a cargo del empleador. AFP/ONP: 13% empleado' }, compliance: { permits: ['Licencia municipal de funcionamiento', 'ITSE (seguridad)', 'Registro sanitario (alimentos/farmacia)', 'Certificado de defensa civil'], sunatObligations: ['Declaración mensual de IGV-Renta', 'Libros electrónicos', 'Comprobantes electrónicos', 'DAOT/COA informativa'], electronicInvoicing: ['Factura electrónica obligatoria (según ingresos)', 'Boleta electrónica', 'Nota de crédito/débito electrónica', 'Usar OSE o SEE-SOL de SUNAT'] }, actionSteps: ['Inscribir RUC en SUNAT', 'Elegir régimen tributario (MYPE recomendado)', 'Obtener licencia municipal', 'Configurar facturación electrónica'] };
}
