/**
 * PIX Integration Advisor skill — Brazil instant payment system setup and optimization.
 * Owner: HeadIntelligenceRisk agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface PixIntegrationAdvice { setup: { requirements: string[]; providers: string[]; apiOptions: string[] }; implementation: { qrCode: string[]; copyPaste: string[]; webhooks: string[] }; optimization: { reconciliation: string[]; fees: string; limits: string[] }; compliance: { bcbRegulations: string[]; fraud: string[]; lgpd: string[] }; actionSteps: string[]; }
export interface PixIntegrationOptions { businessType: string; monthlyVolume?: string; currentPayments?: string; challenges?: string; language?: string; }
const SYSTEM = 'You are a PIX (Brazil instant payments) integration expert. Setup, API implementation, QR codes, webhooks, BCB compliance. Default language: Portuguese/Spanish.';
const FORMAT = 'Respond with JSON: { "setup": { "requirements": [string], "providers": [string], "apiOptions": [string] }, "implementation": { "qrCode": [string], "copyPaste": [string], "webhooks": [string] }, "optimization": { "reconciliation": [string], "fees": string, "limits": string[] }, "compliance": { "bcbRegulations": [string], "fraud": [string], "lgpd": [string] }, "actionSteps": [string] }';
export async function advisePixIntegration(options: PixIntegrationOptions, llmClient?: LLMClient): Promise<PixIntegrationAdvice> {
  if (llmClient) { const prompt = `PIX integration advice for: ${options.businessType}\nVolume: ${options.monthlyVolume ?? 'unknown'}\n${options.challenges ? `Challenges: ${options.challenges}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as PixIntegrationAdvice; } catch { /* fall through */ } }
  return { setup: { requirements: ['CNPJ ativo', 'Conta bancária PJ', 'Chave PIX registrada (CNPJ, email, ou aleatória)', 'Certificado digital (para API)'], providers: ['Mercado Pago', 'PagSeguro', 'Stripe Brasil', 'Gerencianet/Efí', 'Banco do Brasil API'], apiOptions: ['API PIX do Banco Central (direto)', 'PSP intermediário (mais fácil)', 'Gateway de pagamento (Mercado Pago/Stripe)'] }, implementation: { qrCode: ['QR Code estático: valor fixo, identificador único', 'QR Code dinâmico: valor variável, vencimento, multa', 'Imprimir QR Code no ponto de venda', 'Exibir QR Code no checkout do e-commerce'], copyPaste: ['Gerar código copia-e-cola para cada transação', 'Incluir no WhatsApp como link de pagamento', 'Validade: 24-72 horas recomendado'], webhooks: ['Configurar webhook para confirmação instantânea', 'Validar assinatura do webhook', 'Retry automático em caso de falha', 'Reconciliação: txid único por transação'] }, optimization: { reconciliation: ['Usar txid único por pedido', 'Conciliação automática via webhook', 'Relatório diário de recebimentos', 'Integrar com sistema contábil'], fees: 'PIX para PJ: 0.00% a 1.19% dependendo do PSP (Mercado Pago: 0.99%)', limits: ['Pessoa física: R$1.000/noite (padrão)', 'Pessoa jurídica: sem limite padrão', 'Ajustável no app do banco'] }, compliance: { bcbRegulations: ['Resolução BCB nº 1/2020', 'Manual de Segurança do PIX', 'Notificação de fraude obrigatória'], fraud: ['Mecanismo Especial de Devolução (MED)', 'Monitorar transações atípicas', 'Limite noturno reduzido'], lgpd: ['Proteger dados de chaves PIX', 'Consentimento para armazenar dados', 'Não compartilhar dados de transação'] }, actionSteps: ['Registrar chave PIX com CNPJ', 'Escolher PSP (Mercado Pago para início)', 'Integrar QR Code dinâmico no checkout', 'Configurar webhooks para confirmação automática'] };
}
