/**
 * Podcast Advisor skill — Launch, production, growth, monetization.
 * Owner: CMO agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface PodcastAdvice { launch: { format: string; equipment: string[]; hosting: string[] }; production: { workflow: string[]; editing: string[]; showNotes: string[] }; growth: { distribution: string[]; guestStrategy: string[]; promotion: string[] }; monetization: { models: string[]; milestones: string[]; sponsorshipTips: string[] }; actionSteps: string[]; }
export interface PodcastOptions { topic: string; targetAudience?: string; budget?: string; experience?: string; language?: string; }
const SYSTEM = 'You are a podcast launch and growth advisor for LatAm creators and SMBs. Format, production, distribution, monetization. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "launch": { "format": string, "equipment": [string], "hosting": [string] }, "production": { "workflow": [string], "editing": [string], "showNotes": [string] }, "growth": { "distribution": [string], "guestStrategy": [string], "promotion": [string] }, "monetization": { "models": [string], "milestones": [string], "sponsorshipTips": [string] }, "actionSteps": [string] }';
export async function advisePodcast(options: PodcastOptions, llmClient?: LLMClient): Promise<PodcastAdvice> {
  if (llmClient) { const prompt = `Podcast strategy for: ${options.topic}\nAudience: ${options.targetAudience ?? 'entrepreneurs'}\nBudget: ${options.budget ?? 'low'}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as PodcastAdvice; } catch { /* fall through */ } }
  return { launch: { format: 'Entrevistas semanales (30-45 min) + episodios solo (15-20 min)', equipment: ['Micrófono USB (Audio-Technica ATR2100x ~$80)', 'Audífonos cerrados', 'Riverside.fm o Zencastr (grabación remota)', 'Canva (portada del podcast)'], hosting: ['Spotify for Podcasters (gratis)', 'Buzzsprout ($12/mes)', 'Podbean (gratis hasta 5h/mes)'] }, production: { workflow: ['Lunes: investigar tema + contactar invitado', 'Miércoles: grabar episodio', 'Jueves: editar + show notes', 'Viernes: publicar + promocionar'], editing: ['Descript (editar como texto, $24/mes)', 'Audacity (gratis, más manual)', 'Remover silenciones >2 segundos', 'Normalizar audio a -16 LUFS'], showNotes: ['Resumen de 3-5 bullet points', 'Timestamps de momentos clave', 'Links mencionados', 'CTA + link de suscripción'] }, growth: { distribution: ['Spotify, Apple Podcasts, Google Podcasts', 'YouTube (video o audiograma)', 'iVoox (importante en LatAm/España)'], guestStrategy: ['Invitar expertos con audiencia complementaria', 'Preparar 5 preguntas únicas (no genéricas)', 'Pedir al invitado que comparta el episodio'], promotion: ['Audiograma de 60 seg para Instagram/TikTok', 'Hilo de Twitter con takeaways', 'Newsletter con resumen', 'Cross-promotion con otros podcasts'] }, monetization: { models: ['Sponsors/patrocinadores', 'Contenido premium (Patreon)', 'Servicios propios (consultoría)', 'Afiliados (herramientas mencionadas)'], milestones: ['100 descargas/episodio: buscar micro-sponsors', '500/episodio: sponsors locales', '1000+/episodio: sponsors nacionales'], sponsorshipTips: ['CPM en LatAm: $15-30 USD por 1000 descargas', 'Ofrecer paquetes: pre-roll + mid-roll + show notes', 'Host-read ads convierten 3-5x más que grabados'] }, actionSteps: ['Definir formato y frecuencia', 'Grabar episodio piloto (no publicar)', 'Crear portada y descripción del podcast', 'Publicar primeros 3 episodios de golpe'] };
}
