/**
 * Product Launch Advisor skill — Launch strategy, go-to-market, pricing.
 * Owner: CPO agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface ProductLaunchAdvice { preLaunch: { timeline: string[]; audience: string[]; buzz: string[] }; launch: { channels: string[]; messaging: string[]; offers: string[] }; postLaunch: { feedback: string[]; iteration: string[]; retention: string[] }; metrics: { targets: string[]; tools: string[]; milestones: string[] }; actionSteps: string[]; }
export interface ProductLaunchOptions { productName: string; category?: string; targetMarket?: string; launchDate?: string; budget?: string; language?: string; }
const SYSTEM = 'You are a product launch strategist for LatAm SMBs. Pre-launch buzz, go-to-market, post-launch iteration. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "preLaunch": { "timeline": [string], "audience": [string], "buzz": [string] }, "launch": { "channels": [string], "messaging": [string], "offers": [string] }, "postLaunch": { "feedback": [string], "iteration": [string], "retention": [string] }, "metrics": { "targets": [string], "tools": [string], "milestones": [string] }, "actionSteps": [string] }';
export async function adviseProductLaunch(options: ProductLaunchOptions, llmClient?: LLMClient): Promise<ProductLaunchAdvice> {
  if (llmClient) { const prompt = `Product launch strategy for: ${options.productName}\nCategory: ${options.category ?? 'general'}\nTarget: ${options.targetMarket ?? 'LatAm'}\n${options.budget ? `Budget: ${options.budget}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as ProductLaunchAdvice; } catch { /* fall through */ } }
  return { preLaunch: { timeline: ['8 semanas antes: definir oferta y posicionamiento', '6 semanas: crear landing page + lista de espera', '4 semanas: contenido teaser en redes', '2 semanas: early access a lista VIP', '1 semana: countdown + testimonios beta'], audience: ['Lista de email existente', 'Seguidores en redes sociales', 'Comunidades del nicho (WhatsApp, Facebook, Discord)', 'Clientes actuales (upgrade/cross-sell)'], buzz: ['Teaser content (behind-the-scenes)', 'Beta testers con acceso anticipado', 'Colaboraciones con micro-influencers', 'Countdown en WhatsApp status'] }, launch: { channels: ['WhatsApp broadcast a lista VIP', 'Instagram (Reels + Stories + Post)', 'Email secuencia de 3 días', 'Landing page con urgencia', 'Facebook/Google Ads (retargeting)'], messaging: ['Problema que resuelve (no features)', 'Resultado específico y medible', 'Prueba social (testimonios beta)', 'Urgencia real (stock/tiempo/precio)'], offers: ['Early bird: 30% descuento primeras 48h', 'Bundle: producto + bonus exclusivo', 'Garantía de 30 días', 'Bonus por referidos'] }, postLaunch: { feedback: ['Encuesta a compradores (día 7)', 'Entrevistas 1:1 con 5 clientes', 'Monitorear reviews y comentarios', 'Net Promoter Score (NPS)'], iteration: ['Primer update basado en feedback (semana 3)', 'A/B test de pricing (mes 2)', 'Agregar feature más solicitada (mes 2)', 'Optimizar onboarding según drop-offs'], retention: ['Secuencia de onboarding automática', 'Check-in a los 14 días', 'Comunidad exclusiva de compradores', 'Programa de referidos post-compra'] }, metrics: { targets: ['Ventas día 1: 10% de la lista', 'Conversión landing: >5%', 'CAC < 30% del precio', 'NPS > 40 en mes 1'], tools: ['Google Analytics (tráfico)', 'Hotjar (comportamiento landing)', 'Stripe/MercadoPago (ventas)', 'Typeform (encuestas)'], milestones: ['100 en lista de espera', 'Primeras 10 ventas', '50 clientes activos', 'Primer referido orgánico'] }, actionSteps: ['Definir oferta irresistible (producto + bonus + garantía)', 'Crear landing page con lista de espera', 'Planear contenido teaser para 4 semanas', 'Preparar secuencia de email de lanzamiento'] };
}
