/**
 * PR Writer skill — Press releases, media outreach, crisis comms.
 * Owner: CMO agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface PrWriterAdvice { pressRelease: { structure: string[]; tips: string[]; distribution: string[] }; mediaOutreach: { pitchTemplate: string; mediaList: string[]; followUp: string[] }; crisisComms: { framework: string[]; templates: string[]; doNots: string[] }; measurement: { kpis: string[]; tools: string[]; benchmarks: string[] }; actionSteps: string[]; }
export interface PrWriterOptions { company: string; newsType: string; targetMedia?: string; urgency?: string; language?: string; }
const SYSTEM = 'You are a PR and communications specialist for LatAm SMBs. Press releases, media relations, crisis communications. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "pressRelease": { "structure": [string], "tips": [string], "distribution": [string] }, "mediaOutreach": { "pitchTemplate": string, "mediaList": [string], "followUp": [string] }, "crisisComms": { "framework": [string], "templates": [string], "doNots": [string] }, "measurement": { "kpis": [string], "tools": [string], "benchmarks": [string] }, "actionSteps": [string] }';
export async function writePr(options: PrWriterOptions, llmClient?: LLMClient): Promise<PrWriterAdvice> {
  if (llmClient) { const prompt = `PR strategy for: ${options.company}\nNews: ${options.newsType}\nTarget media: ${options.targetMedia ?? 'local + industry'}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as PrWriterAdvice; } catch { /* fall through */ } }
  return { pressRelease: { structure: ['Titular impactante (max 10 palabras)', 'Subtítulo con contexto', 'Primer párrafo: Qué + Quién + Cuándo + Dónde + Por qué', 'Cita del fundador/CEO', 'Contexto de la empresa (boilerplate)', 'Datos de contacto'], tips: ['Una página máximo', 'Escribir en tercera persona', 'Incluir datos/cifras concretas', 'Enviar entre martes y jueves, 9-11am'], distribution: ['Directo a periodistas del sector', 'PR Newswire / Business Wire', 'Grupos de WhatsApp de periodistas', 'LinkedIn (publicar como artículo)'] }, mediaOutreach: { pitchTemplate: 'Asunto: [Dato impactante] + [Nombre empresa]\n\nHola [Nombre],\n\nVi tu artículo sobre [tema] y pensé que te interesaría:\n\n[1 oración del news hook]\n[1 oración del por qué importa]\n[1 oración de la oferta: entrevista/datos exclusivos]\n\n¿Tienes 15 minutos esta semana?', mediaList: ['Periodistas del sector (investigar en LinkedIn)', 'Medios locales (ciudad/país)', 'Blogs de la industria', 'Newsletters especializadas', 'Podcasts del nicho'], followUp: ['Primer follow-up: 3 días después', 'Segundo follow-up: 1 semana después (con ángulo nuevo)', 'No más de 2 follow-ups por periodista'] }, crisisComms: { framework: ['Reconocer el problema (primeras 2 horas)', 'Comunicar qué pasó (hechos, no especulaciones)', 'Explicar qué estamos haciendo', 'Ofrecer solución/compensación', 'Seguimiento hasta resolución'], templates: ['Disculpa pública (redes sociales)', 'Comunicado a clientes afectados', 'FAQ interna para el equipo', 'Actualización de progreso'], doNots: ['No borrar comentarios negativos', 'No mentir o minimizar', 'No culpar a terceros', 'No ignorar (el silencio amplifica)'] }, measurement: { kpis: ['Menciones en medios', 'Tráfico web desde PR', 'Sentiment de menciones', 'Leads generados'], tools: ['Google Alerts (gratis)', 'Mention.com', 'Google Analytics (UTM tags)'], benchmarks: ['1 mención en medio relevante por comunicado', 'Respuesta de periodistas: 10-20% de pitches'] }, actionSteps: ['Crear media list de 20 periodistas relevantes', 'Escribir boilerplate de la empresa', 'Identificar próximo news hook', 'Enviar primer pitch personalizado'] };
}
