/**
 * Scheduling Advisor skill — Appointment booking, calendar management.
 * Owner: COO agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface SchedulingAdvice { setup: { tools: string[]; integration: string[]; availability: string[] }; booking: { flow: string[]; reminders: string[]; policies: string[] }; optimization: { noShowReduction: string[]; bufferTime: string; batching: string[] }; automation: { triggers: string[]; notifications: string[]; followUp: string[] }; actionSteps: string[]; }
export interface SchedulingOptions { businessType: string; appointmentsPerWeek?: number; currentMethod?: string; challenges?: string; language?: string; }
const SYSTEM = 'You are a scheduling and appointment management expert for LatAm SMBs. Booking flows, calendar optimization, no-show reduction. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "setup": { "tools": [string], "integration": [string], "availability": [string] }, "booking": { "flow": [string], "reminders": [string], "policies": [string] }, "optimization": { "noShowReduction": [string], "bufferTime": string, "batching": [string] }, "automation": { "triggers": [string], "notifications": [string], "followUp": [string] }, "actionSteps": [string] }';
export async function adviseScheduling(options: SchedulingOptions, llmClient?: LLMClient): Promise<SchedulingAdvice> {
  if (llmClient) { const prompt = `Scheduling optimization for: ${options.businessType}\nAppointments/week: ${options.appointmentsPerWeek ?? 'unknown'}\n${options.challenges ? `Challenges: ${options.challenges}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as SchedulingAdvice; } catch { /* fall through */ } }
  return { setup: { tools: ['Calendly (gratis hasta 1 tipo de evento)', 'Cal.com (open source, sin límite)', 'Google Calendar (integración base)', 'TidyCal (pago único $29)'], integration: ['Sincronizar con Google Calendar / Outlook', 'Embed en sitio web / landing page', 'Link en bio de Instagram', 'Botón en WhatsApp Business'], availability: ['Bloques de disponibilidad fijos (ej: L-V 10am-1pm, 3pm-6pm)', 'Buffer entre citas: 15-30 min', 'Bloquear tiempo para trabajo profundo', 'Actualizar disponibilidad semanalmente'] }, booking: { flow: ['1. Cliente hace clic en link de agendamiento', '2. Selecciona tipo de cita + horario', '3. Completa formulario (nombre, teléfono, motivo)', '4. Confirmación automática (email + WhatsApp)', '5. Recordatorio 24h y 1h antes'], reminders: ['24 horas antes: email + WhatsApp', '1 hora antes: WhatsApp', 'Incluir link para reagendar/cancelar', 'Incluir dirección/link de videollamada'], policies: ['Cancelación: mínimo 4 horas antes', 'No-show: cobrar 50% o bloquear reagendamiento', 'Reagendar: máximo 2 veces', 'Pago anticipado para servicios premium'] }, optimization: { noShowReduction: ['Recordatorios dobles (email + WhatsApp)', 'Cobrar depósito al agendar', 'Confirmar asistencia 24h antes', 'Penalizar no-shows repetidos'], bufferTime: '15 minutos entre citas (30 para servicios complejos)', batching: ['Agrupar citas similares en bloques', 'Lunes/miércoles: consultas nuevas', 'Martes/jueves: seguimientos', 'Viernes: admin y planeación'] }, automation: { triggers: ['Nueva cita → email confirmación + WhatsApp', 'Cita completada → encuesta de satisfacción', 'No-show → email de reagendamiento', 'Cancelación → abrir slot para lista de espera'], notifications: ['Al equipo: nueva cita agendada', 'Al cliente: confirmación + recordatorios', 'Al admin: reporte diario de citas', 'Alerta: doble reserva detectada'], followUp: ['Post-cita: email de resumen + próximos pasos', 'Sin reagendar en 7 días: recordatorio', 'Trimestral: invitar a check-up/review', 'Anual: renovación/actualización'] }, actionSteps: ['Elegir herramienta de agendamiento (Cal.com recomendado)', 'Definir tipos de cita y duración', 'Configurar recordatorios automáticos (24h + 1h)', 'Agregar link de agendamiento en WhatsApp + sitio web'] };
}
