/**
 * Shopify Optimizer skill — Store setup, theme, apps, conversion optimization.
 * Owner: HeadGrowth agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface ShopifyOptimization { storeSetup: { theme: string; apps: string[]; settings: string[] }; conversion: { improvements: string[]; checkoutTips: string[]; abandonedCartStrategy: string }; seo: { metaTags: string[]; structuredData: string[]; speedTips: string[] }; integrations: { payments: string[]; shipping: string[]; marketing: string[] }; actionSteps: string[]; }
export interface ShopifyOptions { storeName: string; industry?: string; monthlyRevenue?: string; challenges?: string; language?: string; }
const SYSTEM = 'You are a Shopify optimization expert for LatAm SMBs. Store setup, theme selection, app recommendations, conversion optimization, SEO. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "storeSetup": { "theme": string, "apps": [string], "settings": [string] }, "conversion": { "improvements": [string], "checkoutTips": [string], "abandonedCartStrategy": string }, "seo": { "metaTags": [string], "structuredData": [string], "speedTips": [string] }, "integrations": { "payments": [string], "shipping": [string], "marketing": [string] }, "actionSteps": [string] }';
export async function optimizeShopify(options: ShopifyOptions, llmClient?: LLMClient): Promise<ShopifyOptimization> {
  if (llmClient) { const prompt = `Shopify optimization for: ${options.storeName}\nIndustry: ${options.industry ?? 'general'}\n${options.challenges ? `Challenges: ${options.challenges}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as ShopifyOptimization; } catch { /* fall through */ } }
  return { storeSetup: { theme: 'Dawn (gratuito, rápido, mobile-first)', apps: ['Judge.me (reseñas)', 'Klaviyo (email)', 'PageFly (landing pages)', 'Tidio (chat)'], settings: ['Activar checkout en un paso', 'Configurar moneda local', 'Habilitar Google Analytics 4'] }, conversion: { improvements: ['Fotos de producto de alta calidad (min 5 por producto)', 'Descripciones con beneficios, no solo características', 'Urgencia: stock limitado, ofertas por tiempo'], checkoutTips: ['Permitir checkout como invitado', 'Mostrar sellos de seguridad', 'Ofrecer múltiples métodos de pago'], abandonedCartStrategy: '3 emails: 1h después, 24h después, 72h con descuento 10%' }, seo: { metaTags: ['Título: Producto + Beneficio + Marca (max 60 chars)', 'Descripción: Propuesta de valor + CTA (max 155 chars)'], structuredData: ['Product schema', 'BreadcrumbList', 'Organization'], speedTips: ['Comprimir imágenes (WebP)', 'Limitar apps instaladas', 'Usar lazy loading'] }, integrations: { payments: ['Shopify Payments', 'PayPal', 'Mercado Pago'], shipping: ['ShipStation', 'Shipify'], marketing: ['Meta Pixel', 'Google Ads', 'Klaviyo'] }, actionSteps: ['Instalar tema Dawn y personalizar colores/logo', 'Configurar Mercado Pago como método de pago', 'Crear secuencia de carrito abandonado', 'Optimizar SEO de las 10 páginas principales'] };
}
