/**
 * WhatsApp Business Advisor skill — Catalog, automation, broadcasts, API.
 * Owner: HeadGrowth agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface WhatsAppBusinessAdvice { catalog: { setup: string[]; bestPractices: string[]; categories: string[] }; automation: { welcomeMessage: string; quickReplies: string[]; awayMessage: string; flows: string[] }; broadcasts: { segmentation: string[]; timing: string; templates: string[]; compliance: string[] }; api: { providers: string[]; useCases: string[]; pricing: string }; actionSteps: string[]; }
export interface WhatsAppBusinessOptions { businessType: string; monthlyMessages?: number; country?: string; challenges?: string; language?: string; }
const SYSTEM = 'You are a WhatsApp Business expert for LatAm SMBs. Catalog optimization, automation, broadcast strategies, API migration. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "catalog": { "setup": [string], "bestPractices": [string], "categories": [string] }, "automation": { "welcomeMessage": string, "quickReplies": [string], "awayMessage": string, "flows": [string] }, "broadcasts": { "segmentation": [string], "timing": string, "templates": [string], "compliance": [string] }, "api": { "providers": [string], "useCases": [string], "pricing": string }, "actionSteps": [string] }';
export async function adviseWhatsAppBusiness(options: WhatsAppBusinessOptions, llmClient?: LLMClient): Promise<WhatsAppBusinessAdvice> {
  if (llmClient) { const prompt = `WhatsApp Business advice for: ${options.businessType}\nCountry: ${options.country ?? 'Mexico'}\nMonthly messages: ${options.monthlyMessages ?? 'unknown'}\n${options.challenges ? `Challenges: ${options.challenges}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as WhatsAppBusinessAdvice; } catch { /* fall through */ } }
  return { catalog: { setup: ['Máximo 500 productos', 'Fotos cuadradas 1080x1080', 'Precio en moneda local', 'Descripción corta (max 100 chars)'], bestPractices: ['Actualizar precios semanalmente', 'Organizar por colecciones', 'Incluir variantes como productos separados'], categories: ['Productos físicos', 'Servicios', 'Menú de restaurante', 'Servicios profesionales'] }, automation: { welcomeMessage: '¡Hola! 👋 Bienvenido a [Negocio]. ¿En qué te puedo ayudar?\n1️⃣ Ver catálogo\n2️⃣ Hacer pedido\n3️⃣ Soporte', quickReplies: ['Gracias por tu compra', 'Tu pedido está en camino', 'Horarios: L-V 9am-6pm', 'Métodos de pago disponibles'], awayMessage: 'Estamos fuera de horario. Te respondemos mañana a primera hora.', flows: ['Flujo de pedido: Saludo → Catálogo → Selección → Pago → Confirmación', 'Flujo de soporte: Problema → Categoría → Solución → Seguimiento'] }, broadcasts: { segmentation: ['Clientes activos (compra <30 días)', 'Clientes inactivos (>90 días)', 'Leads nuevos (nunca compraron)', 'VIPs (>3 compras)'], timing: 'Martes a jueves, 10am-12pm o 3pm-5pm (hora local)', templates: ['Promoción semanal', 'Nuevo producto/servicio', 'Recordatorio de pago', 'Encuesta de satisfacción'], compliance: ['Solo enviar a contactos que dieron opt-in', 'Incluir opción de darse de baja', 'Máximo 1 broadcast por semana', 'No enviar después de 8pm'] }, api: { providers: ['360dialog', 'Twilio', 'MessageBird', 'Wati'], useCases: ['Notificaciones transaccionales', 'Chatbot con IA', 'Integración CRM', 'Pagos por WhatsApp'], pricing: 'Conversaciones de marketing: ~$0.05-0.10 USD, Utility: ~$0.02-0.05 USD' }, actionSteps: ['Completar catálogo con fotos y precios', 'Configurar mensaje de bienvenida y respuestas rápidas', 'Segmentar contactos en 4 grupos', 'Programar primer broadcast a clientes activos'] };
}
