/**
 * WooCommerce Advisor skill — Store setup, plugins, performance, payments.
 * Owner: HeadGrowth agent.
 */
import type { LLMClient } from './callTranscription.js';
export interface WooCommerceAdvice { setup: { hosting: string[]; plugins: string[]; theme: string }; performance: { speedTips: string[]; caching: string[]; imageOptimization: string[] }; payments: { gateways: string[]; localMethods: string[]; security: string[] }; marketing: { seoPlugins: string[]; emailIntegration: string[]; socialCommerce: string[] }; actionSteps: string[]; }
export interface WooCommerceOptions { storeName: string; country?: string; productCount?: number; challenges?: string; language?: string; }
const SYSTEM = 'You are a WooCommerce expert for LatAm SMBs. Store optimization, plugin selection, performance, local payment gateways. Default language: Spanish.';
const FORMAT = 'Respond with JSON: { "setup": { "hosting": [string], "plugins": [string], "theme": string }, "performance": { "speedTips": [string], "caching": [string], "imageOptimization": [string] }, "payments": { "gateways": [string], "localMethods": [string], "security": [string] }, "marketing": { "seoPlugins": [string], "emailIntegration": [string], "socialCommerce": [string] }, "actionSteps": [string] }';
export async function adviseWooCommerce(options: WooCommerceOptions, llmClient?: LLMClient): Promise<WooCommerceAdvice> {
  if (llmClient) { const prompt = `WooCommerce advice for: ${options.storeName}\nCountry: ${options.country ?? 'Mexico'}\nProducts: ${options.productCount ?? 'unknown'}\n${options.challenges ? `Challenges: ${options.challenges}\n` : ''}\n${FORMAT}`; const response = await llmClient.complete({ prompt, system: SYSTEM, tier: 'haiku' }); try { return JSON.parse(response.text) as WooCommerceAdvice; } catch { /* fall through */ } }
  return { setup: { hosting: ['SiteGround (LatAm CDN)', 'Cloudways (escalable)', 'Starter: hosting compartido con LiteSpeed'], plugins: ['WooCommerce Payments', 'Yoast SEO', 'WP Rocket', 'Wordfence', 'WPML (multiidioma)'], theme: 'Astra o Kadence (ligeros, compatibles, gratuitos)' }, performance: { speedTips: ['Usar CDN (Cloudflare gratuito)', 'Minimizar plugins activos (<20)', 'PHP 8.1+ y MySQL 8.0+'], caching: ['WP Rocket o LiteSpeed Cache', 'Object cache con Redis', 'Browser caching: 1 año para assets estáticos'], imageOptimization: ['ShortPixel o Imagify (compresión automática)', 'Formato WebP', 'Lazy loading nativo de WordPress'] }, payments: { gateways: ['Mercado Pago', 'PayPal Commerce', 'Stripe'], localMethods: ['OXXO (México)', 'PSE (Colombia)', 'PIX (Brasil)', 'Yappy (Panamá)'], security: ['SSL obligatorio', 'PCI DSS vía gateway', '3D Secure activado'] }, marketing: { seoPlugins: ['Yoast SEO Premium', 'Schema Pro (datos estructurados)'], emailIntegration: ['Mailchimp for WooCommerce', 'Klaviyo'], socialCommerce: ['Facebook for WooCommerce', 'Instagram Shopping', 'Catálogo de WhatsApp'] }, actionSteps: ['Migrar a hosting con LiteSpeed/CDN', 'Instalar WP Rocket + ShortPixel', 'Configurar Mercado Pago como gateway principal', 'Optimizar SEO de categorías principales'] };
}
