/**
 * Daily Brief Generator — Morning summary of wins, blockers, next moves.
 */

import type { KitzKernel } from '../kernel.js';
import type { CadenceReport } from './engine.js';
import { callWorkspaceMcp } from '../tools/mcpClient.js';

export async function generateDailyBrief(kernel: KitzKernel): Promise<CadenceReport> {
  const now = new Date();
  const todayStr = now.toISOString().split('T')[0];

  // Fetch data from MCP
  let summary: Record<string, unknown> = {};
  let orders: Record<string, unknown> = {};

  try {
    summary = await callWorkspaceMcp('business_summary', {}) as Record<string, unknown>;
  } catch { /* use empty */ }

  try {
    orders = await callWorkspaceMcp('list_orders', { limit: 5 }) as Record<string, unknown>;
  } catch { /* use empty */ }

  const sections = [
    {
      title: 'System Status',
      content: `KITZ OS: ${kernel.getStatus().status} | ${kernel.getStatus().toolCount} tools | Uptime: ${kernel.getStatus().uptime}s`,
    },
    {
      title: 'Business Snapshot',
      content: JSON.stringify(summary, null, 2).slice(0, 500),
    },
    {
      title: 'Recent Orders',
      content: JSON.stringify(orders, null, 2).slice(0, 500),
    },
  ];

  const whatsappFormatted = `📋 *DAILY BRIEF — ${todayStr}*\n` +
    `━━━━━━━━━━━━━━━━━━\n\n` +
    `🟢 *System*: ${kernel.getStatus().status}\n` +
    `🔧 Tools: ${kernel.getStatus().toolCount}\n\n` +
    `📊 *Business*: Check dashboard for details\n\n` +
    `🎯 *Next Steps*:\n` +
    `• Review pending orders\n` +
    `• Check follow-up contacts\n` +
    `• Process any pending approvals\n\n` +
    `_Generated by KITZ OS_`;

  return {
    cadence: 'daily',
    generatedAt: now.toISOString(),
    period: todayStr,
    sections,
    whatsappFormatted,
  };
}
