/**
 * Cadence Engine — Schedules daily/weekly/monthly/quarterly reports.
 *
 * Uses node-cron for scheduling. Delivers reports via WhatsApp connector.
 * Each cadence queries real data via MCP and generates structured reports.
 *
 * Schedules (Panama time, UTC-5):
 *   - Daily:     7:00 AM every day
 *   - Weekly:    8:00 AM every Monday
 *   - Monthly:   9:00 AM on the 1st
 *   - Quarterly: 9:00 AM on Jan/Apr/Jul/Oct 1st
 */

import { createSubsystemLogger } from 'kitz-schemas';
import cron from 'node-cron';
import type { KitzKernel } from '../kernel.js';
import { generateDailyBrief } from './daily.js';
import { generateWeeklyScorecard } from './weekly.js';

const log = createSubsystemLogger('engine');

export type CadenceType = 'daily' | 'weekly' | 'monthly' | 'quarterly';

export interface CadenceReport {
  cadence: CadenceType;
  generatedAt: string;
  period: string;
  sections: Array<{
    title: string;
    content: string;
  }>;
  whatsappFormatted: string;
}

// ── Config ──

const WA_CONNECTOR_URL = process.env.WA_CONNECTOR_URL || 'http://localhost:3006';
const CADENCE_ENABLED = process.env.CADENCE_ENABLED !== 'false';
const CADENCE_PHONE = process.env.CADENCE_PHONE || ''; // WhatsApp number to receive reports

export class CadenceEngine {
  private tasks: cron.ScheduledTask[] = [];

  constructor(private kernel: KitzKernel) {}

  start(): void {
    if (!CADENCE_ENABLED) {
      log.info('Engine disabled (set CADENCE_ENABLED=true to activate)');
      return;
    }

    // Daily brief — 7:00 AM every day
    this.tasks.push(
      cron.schedule('0 7 * * *', () => {
        void this.runAndDeliver('daily');
      }, { timezone: 'America/Panama' })
    );

    // Weekly scorecard — 8:00 AM every Monday
    this.tasks.push(
      cron.schedule('0 8 * * 1', () => {
        void this.runAndDeliver('weekly');
      }, { timezone: 'America/Panama' })
    );

    // Monthly — 9:00 AM on the 1st
    this.tasks.push(
      cron.schedule('0 9 1 * *', () => {
        void this.runAndDeliver('monthly');
      }, { timezone: 'America/Panama' })
    );

    // Quarterly — 9:00 AM on Jan 1, Apr 1, Jul 1, Oct 1
    this.tasks.push(
      cron.schedule('0 9 1 1,4,7,10 *', () => {
        void this.runAndDeliver('quarterly');
      }, { timezone: 'America/Panama' })
    );

    log.info(`Engine started — ${this.tasks.length} schedules active`);
    if (CADENCE_PHONE) {
      log.info(`Reports will be delivered to ${CADENCE_PHONE.slice(0, 4)}${'*'.repeat(Math.max(0, CADENCE_PHONE.length - 4))}`);
    }
  }

  stop(): void {
    for (const task of this.tasks) {
      task.stop();
    }
    this.tasks = [];
    log.info('Engine stopped');
  }

  /** Run a cadence and optionally deliver via WhatsApp */
  private async runAndDeliver(cadence: CadenceType): Promise<void> {
    try {
      log.info(`Running ${cadence} report...`);
      const report = await this.runCadence(cadence);

      // Deliver via WhatsApp if phone configured
      if (CADENCE_PHONE && report.whatsappFormatted) {
        await this.deliverViaWhatsApp(report.whatsappFormatted);
      }

      log.info(`${cadence} report delivered`);
    } catch (err) {
      log.error(`${cadence} report failed`, { error: (err as Error).message });
    }
  }

  /** Deliver a message via the WhatsApp connector */
  private async deliverViaWhatsApp(message: string): Promise<void> {
    try {
      await fetch(`${WA_CONNECTOR_URL}/outbound/send`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          phone: CADENCE_PHONE,
          message,
          draftOnly: false,
        }),
        signal: AbortSignal.timeout(15_000),
      });
    } catch (err) {
      log.error('WhatsApp delivery failed', { error: (err as Error).message });
    }
  }

  async runCadence(cadence: CadenceType): Promise<CadenceReport> {
    const now = new Date();

    switch (cadence) {
      case 'daily':
        return generateDailyBrief(this.kernel);
      case 'weekly':
        return generateWeeklyScorecard(this.kernel);
      default:
        return {
          cadence,
          generatedAt: now.toISOString(),
          period: `${cadence} report`,
          sections: [{ title: 'Coming Soon', content: `${cadence} reports will be available in beta.` }],
          whatsappFormatted: `*${cadence.toUpperCase()} REPORT*\n\nComing soon in beta.\n\n_Generated by KITZ OS_`,
        };
    }
  }
}
