/**
 * Weekly Scorecard Generator — KPI deltas, pipeline, completion rate.
 */

import type { KitzKernel } from '../kernel.js';
import type { CadenceReport } from './engine.js';
import { callWorkspaceMcp } from '../tools/mcpClient.js';

export async function generateWeeklyScorecard(kernel: KitzKernel): Promise<CadenceReport> {
  const now = new Date();
  const weekStart = new Date(now);
  weekStart.setDate(weekStart.getDate() - 7);

  let summary: Record<string, unknown> = {};
  try {
    summary = await callWorkspaceMcp('business_summary', {}) as Record<string, unknown>;
  } catch { /* use empty */ }

  const sections = [
    {
      title: 'Weekly KPIs',
      content: JSON.stringify(summary, null, 2).slice(0, 800),
    },
  ];

  const whatsappFormatted = `📊 *WEEKLY SCORECARD*\n` +
    `━━━━━━━━━━━━━━━━━━\n` +
    `Period: ${weekStart.toISOString().split('T')[0]} → ${now.toISOString().split('T')[0]}\n\n` +
    `📈 *KPIs*: Check dashboard for details\n\n` +
    `_Generated by KITZ OS_`;

  return {
    cadence: 'weekly',
    generatedAt: now.toISOString(),
    period: `${weekStart.toISOString().split('T')[0]} to ${now.toISOString().split('T')[0]}`,
    sections,
    whatsappFormatted,
  };
}
